"""initial models

Revision ID: 530fb7874dec
Revises: a33424607277
Create Date: 2024-09-17 23:24:08.460275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530fb7874dec'
down_revision = 'a33424607277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
