"""initial migration

Revision ID: 81d22b4ab468
Revises: 
Create Date: 2024-09-11 11:08:39.013654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d22b4ab468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('artist_id'),
    sa.UniqueConstraint('artist_id')
    )
    op.create_table('genre',
    sa.Column('genres_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genres_id'),
    sa.UniqueConstraint('genres_id')
    )
    op.create_table('venue',
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('venue_id'),
    sa.UniqueConstraint('venue_id')
    )
    op.create_table('artist_genres',
    sa.Column('genres_id', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.ForeignKeyConstraint(['genres_id'], ['genre.genres_id'], ),
    sa.PrimaryKeyConstraint('genres_id', 'artist_id')
    )
    op.create_table('show',
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.venue_id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    op.create_table('venue_genres',
    sa.Column('genres_id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['genres_id'], ['genre.genres_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.venue_id'], ),
    sa.PrimaryKeyConstraint('genres_id', 'venue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genres')
    op.drop_table('show')
    op.drop_table('artist_genres')
    op.drop_table('venue')
    op.drop_table('genre')
    op.drop_table('artist')
    # ### end Alembic commands ###
